### ISSUE TITLE
Blocked by malware protection on macOS Catalina

### ISSUE THREAD

**Issue by aengl** [deanishe/alfred-firefox#1]
Thank you for your work, it looks very promising!

When running a search, I get the following error after typing the first letter after `bm ` (or any other keyword):

<img width="532" alt="Screenshot 2020-01-10 at 11 50 48" src="https://user-images.githubusercontent.com/5022924/72143525-8573d900-339f-11ea-9866-6fd13cd88c9f.png">

Running macOS Catalina 10.15.2 (19C57) with v0.1.0 of the Firefox Assistant

**Comment by deanishe** [comment]
That's to be expected on Catalina. [Try these possible fixes](https://github.com/deanishe/alfred-sublime-text/issues/20#issuecomment-549022775).

Additional messing about might be necessary, as Firefox also needs to be able to run the `alfred-firefox` binary to communicate with the workflow.

I make no guarantees the workflow will run on Catalina, however.

**Comment by joeynotjoe** [comment]
Just here to say, I have Alfred 4 added to the [System Preferences > Security & Privacy > Developer Tools window,](https://i.imgur.com/q49ySCn.png) and I didn't get this popup on my Catalina install, and the workflow is working like a charm. Thanks!
