### ISSUE TITLE
No such file or directory when running 'ffass > Install Firefox Extension'

### ISSUE THREAD

**Issue by Nrevi** [deanishe/alfred-firefox#3]
![image](https://user-images.githubusercontent.com/45831601/74332273-503b1c00-4d8d-11ea-9216-8d4e929d9d96.png)

I tried reinstalling the workflow and the firefox extension but that did not fix it.

**Comment by Nrevi** [comment]
When i run alfred-firefox in finder, i get the following errors:

nikodem@Nikodems-MacBook-Pro ~ % /Users/nikodem/Library/Application\ Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A6F257C0-5E96-41AA-94CA-76CE474B0669/alfred-firefox ; exit;
panic: invalid Workflow environment: alfred_workflow_bundleid is not set, alfred_workflow_cache is not set, alfred_workflow_data is not set

goroutine 1 [running]:
github.com/deanishe/awgo.NewFromEnv(0x0, 0x0, 0xc0000aac00, 0x3, 0x3, 0xc0000aac00)
	/Users/daj/pkg/mod/github.com/deanishe/awgo@v0.22.0/workflow.go:159 +0xbe3
github.com/deanishe/awgo.New(0xc0000aac00, 0x3, 0x3, 0xc0000aabe0)
	/Users/daj/pkg/mod/github.com/deanishe/awgo@v0.22.0/workflow.go:149 +0x47
main.init()
	/Users/daj/Code/Alfred/alfred-firefox-assistant/main.go:54 +0x325

[Process completed]

**Comment by Nrevi** [comment]
I managed to find the log file and here's the error: 15:27:21 ---------------- END STACK TRACE -----------------
15:27:21 Sent 1 result(s) to Alfred
15:27:21 [ERROR] open /Users/nikodem/Library/Application Support/Mozilla/NativeMessagingHosts/net.deanishe.alfred.firefox.json: no such file or directory
15:27:21 Get help at https://github.com/deanishe/alfred-firefox/issues
15:27:21 ------------------- 7.918355ms -------------------

**Comment by deanishe** [comment]
Run `ffass > Install Firefox Extension` doesn't mean type that into Alfred. It means type `ffass` into Alfred, and then choose the `Install Firefox Extension` item.

**Comment by Nrevi** [comment]
Ok so i tried that just now, and I'm getting the following trace:

https://pastebin.com/AdExcKu5

**Comment by Nrevi** [comment]
Also it is worth pointing out I don't have an 'install firefox extension' item:
https://imgur.com/a/TwtxsSM

**Comment by deanishe** [comment]
> Also it is worth pointing out I don't have an 'install firefox extension' item

Of course not. The workflow is crashing.

Which version of Firefox do you have installed?

Can you check that this directory exists: `/Users/nikodem/Library/Application Support/Mozilla/NativeMessagingHosts`?

**Comment by Nrevi** [comment]
<img width="753" alt="Screenshot 2020-02-12 at 20 41 37" src="https://user-images.githubusercontent.com/45831601/74375364-12171a00-4dd8-11ea-93e9-b3051fecbe83.png">
<img width="882" alt="Screenshot 2020-02-12 at 20 42 10" src="https://user-images.githubusercontent.com/45831601/74375403-265b1700-4dd8-11ea-95d8-0768ea525ac4.png">

Yeah, that directory doesn't exist for me.

**Comment by deanishe** [comment]
Create it, and the workflow should work.

**Comment by Nrevi** [comment]
That worked! Thank you so much.
