### ISSUE TITLE
"Query too short" error recurring with history search

### ISSUE THREAD

**Issue by bdimaggio** [deanishe/alfred-firefox#36]
Hey all--This is a support request, I'm pretty sure, and not something that is wrong with the workflow/extension. Which is, by the way, absolutely incredible and a huge benefit to my daily work. So, thank you for that!

The issue: I had FF history working great for probably 6 mos. Maybe a month ago, it suddenly began telling me, "Query too short, Please enter at least 3 characters," no matter how long my search string was. Figuring it was a result of some Alfred update I had unthinkingly installed, I removed and re-installed both the workflow and the FF extension. History was back and working fine, but only for a few days. Soon, the "Query too short" error recurred. Any idea how I can debug/fix this? Thank you for any pointers!

_Edit:_ I've found that simply disabling and immediately re-enabling the extension consistently fixes this problem for me. (It recurs every 2-3 months, but with a fix this simple that's no big deal.)

**Comment by sishuoyang** [comment]
I am facing exactly the same problem.

**Comment by kodyabbott** [comment]
I too have started to have this problem about the same time as you. I think Alfred may have updated.

Disabling the extension on Firefox and re-enabling it fixed for me.

If you still are having issues you can debug by following these steps:

Steps to debug:

1. Open Alfred Preferences
2. Go to Workflows and click on Firefox Assistant
3. In the top right click the debug icon (looks like a bug)
4. Then once debug window is open you can test the Firefox Assistant, ie the bm shortcut and get an output from the debug console which should update live as you type.

**Comment by ghost** [comment]
Has the same issue with bookmark search and the new Alfred 5.0.1. Restarting the Extension fixed the issue!

**Comment by bdimaggio** [comment]
Reporting back, way after the fact (something was screwy with my GH email prefs so I didn't see replies until now) -- reinstalled for the third (?) time and this time it has continued to work fine. Not sure what changed in the interim 🤷🏻

**Comment by slippman** [comment]
Just chiming in that I had the same issue (For me it was the bookmark search), found this thread, and quickly got it working again! Thanks all! 
(I just disabled the extension in Firefox and re-enabled it)..

**Comment by bdimaggio** [comment]
More data, fwiw: it happened again yesterday; disable/enable fixed it right away. Perhaps all that reinstalling I did before wasn't necessary.
