### ISSUE TITLE
No longer connecting after newest FF update. Downgrade required?

### ISSUE THREAD

**Issue by yarub123** [deanishe/alfred-firefox#39]
FF 104.0.2
Prior was 103.0.2 and it worked fine. Might need to downgrade at this point, this extension is the sauce. Period. 

Simply does not connect to extension, I've rechecked the preferences location on my computer (not on a cloud), as well as reinstalled workflow/Alfred. 

Issue ONLY came up after the FF update.

Prior issue someone had was similar error message that I received. He resolved it by checking preferences was local and not cloud. Unfortunately that's not what's causing the issue for me. 

Workflow is up to date and registered with FF. 

<img width="804" alt="Screen Shot 2022-09-12 at 11 25 46 PM" src="https://user-images.githubusercontent.com/84487964/189825956-1f325995-7b16-4c17-8965-cb306689834d.png">

**Comment by genseric** [comment]
did you solve this?

**Comment by edgargressie** [comment]
@yarub123 we have the same issue, did you solve it?

**Comment by yarub123** [comment]
@edgargressie Sorry I haven't been checking notifications. Do you still have the issue? If so, please give me your debug output. Also did you create a new firefox profile, or are you using a firefox fork?

**Comment by yarub123** [comment]
Hey guys, @genseric @edgargressie Sorry I haven't been checking notifications. I just saw your responses today. Do you still have the issue? If so, please give me your debug output. Also did you create a new firefox profile, or are you using a firefox fork or more than one Firefox on your computer?

**Comment by genseric** [comment]
hello @yarub123 ,

this is the alfred debug output: 

`
[12:48:35.241] Firefox Assistant[Script Filter] Queuing argument '(null)'
[12:48:35.833] Firefox Assistant[Script Filter] Script with argv '(null)' finished
[12:48:35.840] STDERR: Firefox Assistant[Script Filter] 12:48:35 workflow_paths.go:143: [warning] info.plist not found. Guessed: /Users/USER/Library/CloudStorage/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.FEFC0E29-55CB-4F74-9CAE-4D2315EF7329
🍺
12:48:35 workflow.go:328: ----- Firefox Assistant/0.2.2 (AwGo/0.27.1) ------
12:48:35 actions.go:83: loaded URL action "Open in Chrome" from "~/Library/CloudStorage/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.FEFC0E29-55CB-4F74-9CAE-4D2315EF7329/scripts/Open in Chrome.sh"
12:48:35 actions.go:83: loaded URL action "Open in Default Application" from "~/Library/CloudStorage/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.FEFC0E29-55CB-4F74-9CAE-4D2315EF7329/scripts/Open in Default Application.sh"
12:48:35 actions.go:83: loaded URL action "Open in Firefox" from "~/Library/CloudStorage/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.FEFC0E29-55CB-4F74-9CAE-4D2315EF7329/scripts/Open in Firefox.sh"
12:48:35 actions.go:83: loaded URL action "Open in Safari" from "~/Library/CloudStorage/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.FEFC0E29-55CB-4F74-9CAE-4D2315EF7329/scripts/Open in Safari.sh"
12:48:35 update.go:198: latest version: 0.2.2
12:48:35 feedback.go:481: Sent 7 result(s) to Alfred
12:48:35 workflow.go:405: ------------------- 7.797458ms -------------------
[12:48:35.843] Firefox Assistant[Script Filter] {
  "variables": {
    "AW_SESSION_ID": "J7ICWRJDFZUACAAG4JFZSNXW"
  },
  "items": [
    {
      "title": "No Connection to Browser",
      "subtitle": "dial unix /tmp/alfred-firefox.501.sock: connect: no such file or directory",
      "valid": false,
      "icon": {
        "path": "icons/error.png"
      }
    },
    {
      "title": "Register Workflow with Browser",
      "subtitle": "Use if you've updated or moved the workflow and it isn't working",
      "autocomplete": "workflow:register",
      "valid": false,
      "icon": {
        "path": "icons/install.png"
      }
    },
    {
      "title": "Install Browser Extension",
      "subtitle": "Get the browser extension to integrate this workflow with Firefox",
      "arg": "https://addons.mozilla.org/en-US/firefox/addon/alfred-launcher-integration/",
      "valid": true,
      "icon": {
        "path": "icons/addon.png"
      },
      "variables": {
        "ACTION": "Open in Firefox",
        "CMD": "url",
        "URL": "https://addons.mozilla.org/en-US/firefox/addon/alfred-launcher-integration/"
      }
    },
    {
      "title": "Workflow is Up to Date",
      "valid": false,
      "icon": {
        "path": "icons/update-ok.png"
      }
    },
    {
      "title": "Open Scripts Directory",
      "subtitle": "Open custom scripts directory in Finder",
      "arg": "/Users/USER/Library/Application Support/Alfred/Workflow Data/net.deanishe.alfred.firefox-assistant/scripts",
      "valid": true,
      "icon": {
        "path": "icons/script.png"
      },
      "variables": {
        "ACTION": "Open in Default Application",
        "CMD": "url",
        "URL": "/Users/USER/Library/Application Support/Alfred/Workflow Data/net.deanishe.alfred.firefox-assistant/scripts"
      }
    },
    {
      "title": "Documentation",
      "subtitle": "Open documentation in your browser",
      "arg": "https://github.com/deanishe/alfred-firefox/issues",
      "valid": true,
      "icon": {
        "path": "icons/docs.png"
      },
      "variables": {
        "ACTION": "Open in Firefox",
        "CMD": "url",
        "URL": "https://github.com/deanishe/alfred-firefox/blob/master/doc/index.md"
      }
    },
    {
      "title": "Report Issue",
      "subtitle": "Open issue tracker in your browser",
      "arg": "https://github.com/deanishe/alfred-firefox/issues",
      "valid": true,
      "icon": {
        "path": "icons/issue.png"
      },
      "variables": {
        "ACTION": "Open in Firefox",
        "CMD": "url",
        "URL": "https://github.com/deanishe/alfred-firefox/issues"
      }
    }
  ]
}
[12:48:41.300] Firefox Assistant[Script Filter] Queuing argument 'workflow:register'
[12:48:41.402] Firefox Assistant[Script Filter] Script with argv 'workflow:register' finished
[12:48:41.409] STDERR: Firefox Assistant[Script Filter] 12:48:41 workflow_paths.go:143: [warning] info.plist not found. Guessed: /Users/USER/Library/CloudStorage/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.FEFC0E29-55CB-4F74-9CAE-4D2315EF7329
🍺
12:48:41 workflow.go:328: ----- Firefox Assistant/0.2.2 (AwGo/0.27.1) ------
12:48:41 actions.go:83: loaded URL action "Open in Chrome" from "~/Library/CloudStorage/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.FEFC0E29-55CB-4F74-9CAE-4D2315EF7329/scripts/Open in Chrome.sh"
12:48:41 actions.go:83: loaded URL action "Open in Default Application" from "~/Library/CloudStorage/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.FEFC0E29-55CB-4F74-9CAE-4D2315EF7329/scripts/Open in Default Application.sh"
12:48:41 actions.go:83: loaded URL action "Open in Firefox" from "~/Library/CloudStorage/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.FEFC0E29-55CB-4F74-9CAE-4D2315EF7329/scripts/Open in Firefox.sh"
12:48:41 actions.go:83: loaded URL action "Open in Safari" from "~/Library/CloudStorage/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.FEFC0E29-55CB-4F74-9CAE-4D2315EF7329/scripts/Open in Safari.sh"
12:48:41 magic.go:135: Registered. Re-open Firefox extension to connect.
12:48:41 feedback.go:481: Sent 1 result(s) to Alfred
12:48:41 main.go:202: wrote native app manifest to "~/Library/Application Support/Mozilla/NativeMessagingHosts/net.deanishe.alfred.firefox.json"
12:48:41 main.go:203: 
{
  "name": "net.deanishe.alfred.firefox",
  "description": "Alfred plugin for Firefox",
  "path": "/Users/USER/Library/CloudStorage/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.FEFC0E29-55CB-4F74-9CAE-4D2315EF7329/server.sh",
  "type": "stdio",
  "allowed_extensions": [
    "alfredfirefox@deanishe.net"
  ]
}
12:48:41 workflow.go:405: ------------------- 6.690958ms -------------------
[12:48:41.410] Firefox Assistant[Script Filter] {
  "variables": {
    "AW_SESSION_ID": "J7ICWRJDFZUACAAG4JFZSNXW"
  },
  "items": [
    {
      "title": "Registered. Re-open Firefox extension to connect.",
      "valid": false,
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/ToolbarInfo.icns"
      }
    }
  ]
}
`

the output on alfred is 
![resim](https://github.com/deanishe/alfred-firefox/assets/649577/adf88ebb-d3fa-4ca2-ab29-6ab3e562ebe9)

this is when i run the server.sh
`
./server.sh

12:52:17 workflow_paths.go:143: [warning] info.plist not found. Guessed: /Users/USER/Library/CloudStorage/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.FEFC0E29-55CB-4F74-9CAE-4D2315EF7329
🍺
12:52:17 workflow.go:328: ----- Firefox Assistant/0.2.2 (AwGo/0.27.1) ------
12:52:17 actions.go:83: loaded URL action "Open in Firefox" from "~/Library/CloudStorage/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.FEFC0E29-55CB-4F74-9CAE-4D2315EF7329/scripts/Open in Firefox.sh"
12:52:17 actions.go:83: loaded URL action "Open in Safari" from "~/Library/CloudStorage/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.FEFC0E29-55CB-4F74-9CAE-4D2315EF7329/scripts/Open in Safari.sh"
12:52:17 actions.go:83: loaded URL action "Open in Chrome" from "~/Library/CloudStorage/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.FEFC0E29-55CB-4F74-9CAE-4D2315EF7329/scripts/Open in Chrome.sh"
12:52:17 actions.go:83: loaded URL action "Open in Default Application" from "~/Library/CloudStorage/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.FEFC0E29-55CB-4F74-9CAE-4D2315EF7329/scripts/Open in Default Application.sh"
[38234] 12:52:17 server.go:112: couldn't parse app name from ""
[38234] 12:52:17 server.go:129: browser="Firefox"
4{"id":"1704880337.1","command":"ping","params":null}[38234] 12:52:17 rpc_server.go:291: serving RPC on "/tmp/alfred-firefox.501.sock" ...
[38234] 12:52:17 firefox.go:137: sent command #1704880337.1 - "ping"
[38234] 12:52:22 util.go:57: 5.001888125s ⧗ ping
[38234] 12:52:22 server.go:149: [ERROR] timeout: "1704880337.1"
`

**Comment by yarub123** [comment]
@genseric Hmm, did you change computers or update your browser recently? I'm thinking it's looking for /tmp/alfred-firefox.501.sock in possibly an old profile that you're no longer using. 

Is the socket file "tmp/alfred-firefox.501.sock" created when you run the "server.sh" script?
Also do you have execute permissions on the script? If not go ahead and give it that through `chmod +x (and drag your server.sh script in here!!)`
or to prevent any admin errors, just run `sudo chmod +x (drag server.sh here)`

(1) Try this
1. Go ahead and try removing the workflow... you can back up your workflow if you would like before deleting it from alfred preferences.
2. uninstall/remove the addon from FF (this will also help fix any permissions you may not have set when you set it up)
3. Are you running any firewall?

(2) or Try this: For the /tmp directory: Check if you even have it:
open your terminal and run the following
`cd /tmp`
`ls -l alfred-firefox.501.sock`

If you don't see the file, which i have a feeling you won't, it means the workflow isn't creating it. 
If you do see the file run the following to give it permissions:
`chmod a+w /tmp/alfred-firefox.501.sock`

If you don't see the file, then there's something wrong with your workflow. I would uninstall it, then go to your System Settings, and give Alfred the proper permissions, such as permissions in Full Disk access, Accessibility, etc. (If you want to know the specific permissions, they should tell you which ones on the Alfred website). After giving permissions, go ahead and restart, then try reinstalling BOTH the workflow, and the addon as per the instructions on main page.
